language: rust
rust:
  - stable
  - nightly-2020-10-05
jobs:
  fast_finish: true
cache: cargo
install:
  - rustup default stable
  - rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-05

script:
  - cargo test

