language: rust
rust:
  - stable
  fast_finish: true
cache: cargo
install:
  - rustup default stable
  - rustup install nightly-2020-10-06
  - rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06

script:
  - cargo test

