language: rust
rust:
  - nightly
jobs:
  fast_finish: true
cache: cargo
install:
  - rustup default stable
  - rustup install nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly

script:
  - cargo test

