language: rust
rust:
- 1.47.0
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
install:
- rustup install nightly-2020-10-01
- rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-01
script:
- ls
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
    secure: VyOKv6veygBg3Uq5ir3kGhw0+vk2HrL9HThUQ5iAt/qYNN4oJMl1He2FYdTx++EpiBFUr6cb5UE+5JIlIWWWcQXBVOg6naCTD0IXdZPKhO38lmwHL3+gLAYkasRo4+WyOVT0nUJ51vmPtljzgUEFK3UY3tDPYPA32mIV5paBR7FN9GkpwkAjj+bWmhVmAAMX1P+QGfSLywaC7uNj7lw9cExIFGuy9sijjQQ17ug0jUmg+TGTbD5lBfSi3LJ+2xe9U9e3YP8RbHid06y4qpxfkj3qtcZT3fZD9394fBSqjDhCs7Q8KfNd02Ra8gbFoU621teVdhywjS+vlhQN2ZUkgKedhmrAqFwn1O50BQirM57FjfbgWvJM7syC7P0pshs3M57K5PkkbCi90yoVWMeZtwpCgOWVVYu0OeVVRYg4+cOCpPhHGKGc//yq/a6VRQFKUMTjnzfofRBAS7Y00S6y70gXI+u0q9zgOzfCluu67Vlx1ZuACcBRLQfY6Um7ZrJ5z6rWK9Q3JYPpI1w8+SLNmh11y7tM4LOUxfcoY4OONaA5gSG9zY9ULHGD/zfg5zjBdQzg9JJwhLZBEa7KBCmUp/Dsvx0og9d1YfpiJ52Ryd+8Se9UWl8Q8Bs+vL3QMOum2Q9u+g2N+vMwYgu7ROwQHiAu+cja63wCDKh2S9y+e6Y=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    all_branches: true
  provider: releases
  skip_cleanup: true