language: rust
rust:
  - 1.47.0
cache: cargo

matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-apple-darwin
    os: osx

install:
  - rustup install nightly-2020-10-01
  - rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-01

script:
#  - cargo test
  - cargo build --release --target $TARGET

