version: 2.1

orbs:
  rust: glotrade/rust@0.1.3

jobs:
  build:
    docker:
      - image: cimg/rust:1.48.0
    steps:
      - rust/checkout_with_submodules
      - rust/update_toolchain:
          toolchain: nightly-2020-10-06
      - run:
          name: "Set WASM target"
          command: rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
      - rust/build:
          release: true
      - run:
          name: "Tar binary"
          command: ./tar_binary.sh
