version: 2.1

orbs:
  rust: glotrade/rust@0.1.3

jobs:
  build:
    docker:
      - image: cimg/rust:1.48.0
    steps:
      - rust/checkout_with_submodules
      - rust/build:
          release: true
