version: 2.1

jobs:
  "Build Subtensor":
    docker: # executor type
      - image: cimg/rust:1.48.0 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
    steps:
      - checkout
      - run: rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
      - run: cd subtensor && rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06 
      - run: WASM_BUILD_TOOLCHAIN=nightly-2020-10-06 cargo build --release

workflows:
  main:
    jobs:
      - "Build Subtensor"
